name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to docker container registry
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_LOGIN_USER }}
        password: ${{ secrets.DOCKER_LOGIN_PASS }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v3
      with:
        context: .
        push: true
        platforms: linux/amd64,linux/arm64
        tags: c92s/hello-flask:latest
